version: '3'
services:
    epm-adapter-ansible:
        container_name: elastest-epm-adapter-ansible
        image: elastest/epm-adapter-ansible
        entrypoint: python -m run --register-adapter elastest-epm elastest-epm-adapter-ansible
        depends_on:
            - elastest-platform-manager
        expose:
            - 50052
        ports:
            - 50052:50052
        networks:
            - elastest
networks:
    elastest:
        driver: bridge