version: '3'
services:
    epm:
        container_name: elastest-epm
        image: elastest/epm
        environment:
            - ET_EDM_ALLUXIO_API=http://edm-alluxio-master:19998/
            - ET_EDM_MYSQL_HOST=edm-mysql
            - ET_EDM_MYSQL_PORT=3306
            - ET_EDM_ELASTICSEARCH_API=http://edm-elasticsearch:9200/
            - ET_EDM_API=http://edm:8080/
            - ET_EPM_API=http://epm:8180/
            - ET_ETM_API=http://etm:8091/
            - ET_ESM_API=http://esm:37005/
            - ET_EIM_API=http://eim:8080/
            - ET_ETM_LSBEATS_HOST=etm-beats
            - ET_ETM_LSBEATS_PORT=5044
            - ET_ETM_LSHTTP_API=http://etm-logstash:5002/
            - ET_ETM_RABBIT_HOST=etm-rabbitmq
            - ET_ETM_RABBIT_PORT=5672
            - ET_EMP_API=http://emp:9000/
            - ET_EMP_INFLUXDB_API=http://emp-influxdb:8086/
            - ET_EMP_INFLUXDB_HOST=emp-influxdb
            - ET_EMP_INFLUXDB_GRAPHITE_PORT=2003
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:rw
        expose:
            - 8180
        ports:
            - 37002:8180
            - 50050:50050
        networks:
            - elastest
    epm-adapter-docker-compose:
        container_name: elastest-epm-adapter-docker-compose
        image: elastest/epm-adapter-docker-compose
        entrypoint: python run.py --register-adapter
        depends_on:
            - epm
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:rw
        ports:
            - 50051:50051
        networks:
            - elastest
networks:
    elastest:
        driver: bridge
