/**
 * NOTE: This class is auto generated by the swagger code generator program (2.2.3).
 * https://github.com/swagger-api/swagger-codegen Do not edit the class manually.
 */
package io.elastest.epm.api;

import io.elastest.epm.model.Key;
import io.swagger.annotations.*;
import java.util.List;
import javax.validation.Valid;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

@javax.annotation.Generated(
  value = "io.swagger.codegen.languages.SpringCodegen",
  date = "2018-03-15T14:35:13.711+01:00"
)
@Api(value = "keys", description = "the keys API")
public interface KeysApi {

  @ApiOperation(
    value = "Uploads a key to the EPM.",
    notes = "This uploads a key to the EPM, so it can be later used when registering workers.",
    response = Key.class,
    tags = {
      "Key",
    }
  )
  @ApiResponses(
    value = {
      @ApiResponse(code = 200, message = "Resource Group creation OK", response = Key.class),
      @ApiResponse(code = 201, message = "Created", response = Void.class),
      @ApiResponse(code = 400, message = "Bad Request", response = Void.class),
      @ApiResponse(code = 401, message = "Unauthorized", response = Void.class),
      @ApiResponse(code = 403, message = "Forbidden", response = Void.class),
      @ApiResponse(code = 404, message = "Not Found", response = Void.class)
    }
  )
  @RequestMapping(
    value = "/keys",
    consumes = {"application/json"},
    method = RequestMethod.POST
  )
  ResponseEntity<Key> addKey(
      @ApiParam(value = "Key in a json", required = true) @Valid @RequestBody Key body);

  @ApiOperation(
    value = "Deletes a Key.",
    notes = "Deletes the Key that matches with a given ID.",
    response = String.class,
    tags = {
      "Key",
    }
  )
  @ApiResponses(
    value = {
      @ApiResponse(code = 200, message = "Key deleted successfully", response = String.class),
      @ApiResponse(code = 204, message = "No Content", response = Void.class),
      @ApiResponse(code = 400, message = "Bad Request", response = String.class),
      @ApiResponse(code = 401, message = "Unauthorized", response = Void.class),
      @ApiResponse(code = 403, message = "Forbidden", response = Void.class),
      @ApiResponse(code = 404, message = "Key not found", response = String.class)
    }
  )
  @RequestMapping(
    value = "/keys/{id}",
    produces = {"*/*"},
    method = RequestMethod.DELETE
  )
  ResponseEntity<String> deleteKey(
      @ApiParam(value = "ID of Key", required = true) @PathVariable("id") String id);

  @ApiOperation(
    value = "Returns all available Keys",
    notes = "",
    response = Key.class,
    responseContainer = "List",
    tags = {
      "Key",
    }
  )
  @ApiResponses(
    value = {
      @ApiResponse(
        code = 200,
        message = "Successful operation",
        response = Key.class,
        responseContainer = "List"
      ),
      @ApiResponse(code = 401, message = "Unauthorized", response = Void.class),
      @ApiResponse(code = 403, message = "Forbidden", response = Void.class)
    }
  )
  @RequestMapping(
    value = "/keys",
    produces = {"application/json"},
    method = RequestMethod.GET
  )
  ResponseEntity<List<Key>> getAllKeys();
}
