/**
 * NOTE: This class is auto generated by the swagger code generator program (2.2.3).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.elastest.epm.api;


import io.elastest.epm.model.Key;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import javax.validation.Valid;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2018-03-07T16:32:01.933+01:00")

@Api(value = "keys", description = "the keys API")
public interface KeysApi {

    @ApiOperation(value = "Uploads a key to the EPM.", notes = "This uploads a key to the EPM, so it can be later used when registering workers.", response = Key.class, tags={ "Key", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Resource Group creation OK", response = Key.class),
        @ApiResponse(code = 201, message = "Created", response = Void.class),
        @ApiResponse(code = 400, message = "Bad Request", response = Void.class),
        @ApiResponse(code = 401, message = "Unauthorized", response = Void.class),
        @ApiResponse(code = 403, message = "Forbidden", response = Void.class),
        @ApiResponse(code = 404, message = "Not Found", response = Void.class) })
    
    @RequestMapping(value = "/keys",
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<Key> addKey(@ApiParam(value = "Key in a json" ,required=true )  @Valid @RequestBody Key body);


    @ApiOperation(value = "Returns all available Keys", notes = "", response = Key.class, responseContainer = "List", tags={ "Key", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Successful operation", response = Key.class, responseContainer = "List"),
        @ApiResponse(code = 401, message = "Unauthorized", response = Void.class),
        @ApiResponse(code = 403, message = "Forbidden", response = Void.class) })
    
    @RequestMapping(value = "/keys",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<List<Key>> getAllKeys();

}
